### ISSUE TITLE
Missing Perl requirements when running from Bugzilla master

### ISSUE THREAD

**Issue by edmorley** [dklawren/docker-bugzilla#2]
Can't locate Email/Sender/Simple.pm in @INC (you may need to install the Email::Sender::Simple module) (@INC contains: . lib/x86_64-linux-thread-multi lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at Bugzilla/Mailer.pm line 27.
BEGIN failed--compilation aborted at Bugzilla/Mailer.pm line 27.

**Comment by tvikram1258** [comment]
how to resolve this issue can i get the solution

**Comment by tvikram1258** [comment]
Can't locate Email/Sender/Simple.pm in @INC (@INC contains: . lib/x86_64-linux-thread-multi lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at Bugzilla/Mailer.pm line 27.
BEGIN failed--compilation aborted at Bugzilla/Mailer.pm line 27.
Compilation failed in require at Bugzilla/Auth.pm line 22.
BEGIN failed--compilation aborted at Bugzilla/Auth.pm line 22.
Compilation failed in require at Bugzilla.pm line 23.
BEGIN failed--compilation aborted at Bugzilla.pm line 23.
Compilation failed in require at /var/www/html/bugzilla/index.cgi line 15.
BEGIN failed--compilation aborted at /var/www/html/bugzilla/index.cgi line 15.
